resources:
  App\Entity\Suggestion:
    collectionOperations:
      get: ~
      post:
        validation_groups:
          - post
    itemOperations:
      get: ~
      patch:
        openapi_context:
          summary: Mark a suggestion as discarded or not
          description: Set a Suggestion to be discarded so they can be filtered out
          requestBody:
            content:
              application/merge-patch+json:
                schema:
                  type: object
                  properties:
                    discarded: { type: boolean }
