name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mariadb:
        image: mariadb
        ports:
          - 3306
        env:
          MYSQL_DATABASE: suggestion-box-test
          MYSQL_ROOT_PASSWORD: test
          
    steps:
    - uses: actions/checkout@v2
    
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Verify MariaDB connection
      env:
        PORT: ${{ job.services.mariadb.ports[3306] }}
      run: |
        while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
          sleep 1
        done
    
    - name: Run PHPUnit
      run: ${{ github.workspace }}/vendor/bin/phpunit
    
#     - name: Install DB
#       env:
#         APP_ENV: test
#       run: bin/console doctrine:migrations:migrate -e test -n
